#!/bin/bash
#SBATCH --job-name=sae_setup
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=logs/%x_%j.out

# makes the conda env and installs everything.
set -e

module purge
module load 2023
module load Anaconda3/2023.07-2
source $(conda info --base)/etc/profile.d/conda.sh

if ! conda env list | grep -q ieia; then
    conda create -y -n ieia python=3.11
fi
conda activate ieia
cd $HOME/miniproject
pip install -r requirements.txt
